---@class framework.ui.settings
local M = {}

M.DEFAULT_IMAGE = nil
M.DEFAULT_TEXT_FONT = nil
M.DEFAULT_TEXT_FONT_SIZE = 0.14
M.DEFAULT_TEXT_ALIGN = "center"
M.TEXT_GET_TEXT_PIXEL_SIZE_WIDTH_SCALE = 1.8
M.TEXT_GET_TEXT_PIXEL_SIZE_HEIGHT_SCALE = 3.4
M.DEFAULT_EDITBOX_FRAME = nil
M.DEFAULT_SLIDER_X_FRAME = nil
M.DEFAULT_SLIDER_Y_FRAME = nil
M.DEFAULT_SLOT_IMAGE_IMAGE = nil
M.DEFAULT_SLOT_PROGRESS_IMAGE = nil
M.DEFAULT_SLOT_BACKGROUND_IMAGE = nil
M.DEFAULT_COOLDOWN_READY_IMAGE = nil
M.DEFAULT_COOLDOWN_PROGRESS_IMAGE = nil
M.DEFAULT_TIP_FONT_SIZE = 10
M.DEFAULT_TIP_BACKGROUND_IMAGE = nil
M.DEFAULT_TIP_BORDER_IMAGE = nil

return M
